complete -c weylus -n "__fish_use_subcommand" -l access-code -d 'Access code'
complete -c weylus -n "__fish_use_subcommand" -l bind-address -d 'Bind address'
complete -c weylus -n "__fish_use_subcommand" -l web-port -d 'Web port'
complete -c weylus -n "__fish_use_subcommand" -l websocket-port -d 'Websocket port'
complete -c weylus -n "__fish_use_subcommand" -l custom-index-html -d 'Use custom template of index.html to be served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -l custom-access-html -d 'Use custom access.html to be served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -l custom-style-css -d 'Use custom style.css to be served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -l custom-lib-js -d 'Use custom lib.js to be served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -l completions -d 'Print shell completions for given shell.'
complete -c weylus -n "__fish_use_subcommand" -l try-vaapi -d 'Try to use hardware acceleration through the Video Acceleration API.'
complete -c weylus -n "__fish_use_subcommand" -l try-nvenc -d 'Try to use Nvidia\'s NVENC to encode the video via GPU.'
complete -c weylus -n "__fish_use_subcommand" -l auto-start -d 'Start Weylus server immediately on program start.'
complete -c weylus -n "__fish_use_subcommand" -l no-gui -d 'Run Weylus without gui and start immediately.'
complete -c weylus -n "__fish_use_subcommand" -l wayland-support -d 'Wayland/PipeWire Support.'
complete -c weylus -n "__fish_use_subcommand" -l print-index-html -d 'Print template of index.html served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -l print-access-html -d 'Print access.html served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -l print-style-css -d 'Print style.css served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -l print-lib-js -d 'Print lib.js served by Weylus.'
complete -c weylus -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c weylus -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
